#!/usr/bin/env python3
"""Finds code of the reference corpora in the sources of this repository.

usage: borrow-audit.py --ref LIST [--allowed LIST] [--report FILE] [--max] PATH...
       borrow-audit.py --ref LIST [--allowed LIST] --git-range A..B    (every Pascal file that each commit of the
                                                                       range adds or changes, as that commit has it)

LIST names one reference source per line (tools/audit/fetch-corpora.sh writes it): Pascal (.pas .pp .inc) and C/C++
(.c .cc .cpp .h .hpp) files. PATH is a file or a directory (its .pas, .pp, .inc files). Three comparisons are made; a
match of any of them is printed with both places and makes the exit code 1:

  raw   the tokens of the Pascal text (comments, layout and letter case do not count), against the Pascal references:
        a chain of RAW_K tokens or more in common is a copy.
  ren   the same with every identifier made one and the same token, every literal another: a copy whose names were
        changed. Chains of REN_K tokens or more of which at least REN_WORDS (a share) are identifiers and keywords (a
        table of numbers is like any other table).
  lit   the sequence of the literals alone (strings, characters, numbers, by their values) against the C/C++
        references: what a translation from another language keeps (tables, codes, messages). A routine heading
        ends a sequence. A run of LIT_K literals or more counts when it has LIT_DISTINCT different significant values (numbers of 32 and more,
        texts of two characters and more: bit numbers, coordinates and small counts match anything) and is not a
        count (most neighbours one apart, as the numbers of an enumeration).

A file whose first line says "Generated by tools/NAME" is not compared when tools/NAME exists in the repository: it
is checked by running its generator again (CI), so its content is what the generator makes of its public data.

--allowed names the sources the repository may use (for tv3: magiblot/tvision, the specification of the far2l
extensions, the documents of standards in tools/audit/facts/): a window that occurs in one of them is not counted,
whatever else it occurs in. Documents (.md, .txt) give literals only: numbers (decimal, 0x, $, U+) and quoted text.

The heading of a routine (procedure, function, constructor, destructor, operator: from the keyword to the semicolon
that ends it, with its directives) is a token that matches nothing in raw and ren, so no chain goes over it: an
override has to repeat the signature of the API it overrides.

--max prints, for each comparison, the longest run found in each file (to calibrate the limits, which the options
--raw-k, --ren-k, --lit-k, --lit-distinct change).
"""
import argparse, os, re, sys

RAW_K = 24
REN_K = 200
REN_WORDS = 0.4
LIT_K = 12
LIT_DISTINCT = 6

PAS = ('.pas', '.pp', '.inc')
CPP = ('.c', '.cc', '.cpp', '.cxx', '.h', '.hpp', '.hh')
DOC = ('.md', '.txt')
DOCTOK = re.compile(r"""
   (?P<num>(?:0[xX]|\$|[uU]\+)[0-9a-fA-F]+|\b\d+\b)
 | `(?P<bq>[^`\n]+)`
 | '(?P<sq>[^'\n]+)'
 | "(?P<dq>[^"\n]+)"
""", re.X)


def doc_literals(path):
    text = open(path, encoding='utf-8', errors='replace').read()
    line = lines_of(text)
    out = []
    for m in DOCTOK.finditer(text):
        k = m.lastgroup
        v = m.group(k)
        if k == 'num':
            w = v.lower()
            n = int(w[2:], 16) if w[:2] in ('0x', 'u+') else int(w[1:], 16) if w[0] == '$' else int(w)
            out.append((str(n), line(m.start())))
        else:
            out.append((str(ord(v)) if len(v) == 1 else 's:' + v, line(m.start())))
    return out

TOK = re.compile(r"""
   (?P<str>(?:'(?:[^']|'')*'|\#\$?[0-9a-fA-F]+)+)
 | (?P<num>\$[0-9a-fA-F]+|&[0-7]+|%[01]+|\d+(?:\.\d+)?(?:[eE][+-]?\d+)?)
 | (?P<id>[A-Za-z_][A-Za-z0-9_]*)
 | (?P<sym>:=|<=|>=|<>|\.\.|[^\sA-Za-z0-9_])
""", re.X)
CTOK = re.compile(r"""
   (?P<str>(?:[LuU]8?|u8)?"(?:[^"\\\n]|\\.)*")
 | (?P<chr>(?:[LuU]8?)?'(?:[^'\\\n]|\\.)+')
 | (?P<num>0[xX][0-9a-fA-F']+[uUlL]*|0[bB][01']+[uUlL]*|\d[\d']*(?:\.\d+)?(?:[eE][+-]?\d+)?[uUlLfF]*)
 | (?P<id>[A-Za-z_][A-Za-z0-9_]*)
 | (?P<sym>\S)
""", re.X)
KEYWORDS = set("""and array asm begin case const constructor destructor div do downto else end except exports file
finally for function goto if implementation in inherited inline interface label library mod nil not object of or
packed procedure program property record repeat set shl shr string then to try type unit until uses var while with
xor class private protected public published""".split())
HEADS = {'procedure', 'function', 'constructor', 'destructor', 'operator'}
DIRECTIVES = {'override', 'virtual', 'abstract', 'overload', 'reintroduce', 'static', 'inline', 'cdecl', 'stdcall',
              'register', 'pascal', 'safecall', 'forward', 'assembler', 'dynamic', 'message', 'deprecated', 'platform',
              'final', 'varargs', 'local', 'nostackframe', 'interrupt', 'far', 'near', 'export'}


def strip_pascal(t):
    """The text without comments; line breaks are kept."""
    out, i, n = [], 0, len(t)
    while i < n:
        c = t[i]
        if c == "'":
            j = i + 1
            while j < n:
                if t[j] == "'":
                    if j + 1 < n and t[j + 1] == "'":
                        j += 2
                        continue
                    break
                if t[j] == '\n':
                    break
                j += 1
            out.append(t[i:j + 1])
            i = j + 1
        elif c == '{' or t.startswith('(*', i) or t.startswith('//', i):
            end = {'{': '}', '(': '*)', '/': '\n'}[c]
            j = t.find(end, i + 1)
            j = n if j < 0 else (j if end == '\n' else j + len(end))
            out.append(' ' + '\n' * t.count('\n', i, j))
            i = j
        else:
            out.append(c)
            i += 1
    return ''.join(out)


def strip_c(t):
    out, i, n = [], 0, len(t)
    while i < n:
        c = t[i]
        if c in '"\'':
            j = i + 1
            while j < n and t[j] != c and t[j] != '\n':
                j += 2 if t[j] == '\\' else 1
            out.append(t[i:j + 1])
            i = j + 1
        elif t.startswith('//', i) or t.startswith('/*', i):
            j = t.find('\n' if t[i + 1] == '/' else '*/', i + 2)
            j = n if j < 0 else (j if t[i + 1] == '/' else j + 2)
            out.append(' ' + '\n' * t.count('\n', i, j))
            i = j
        else:
            out.append(c)
            i += 1
    return ''.join(out)


def pas_literal(kind, v):
    """The value of a Pascal literal: a number as a decimal string, a string as its characters."""
    if kind == 'num':
        try:
            if v[0] == '$':
                return str(int(v[1:], 16))
            if v[0] == '&':
                return str(int(v[1:], 8))
            if v[0] == '%':
                return str(int(v[1:], 2))
            return str(int(v)) if v.isdigit() else v
        except ValueError:
            return v
    s, i = [], 0
    while i < len(v):
        if v[i] == "'":
            j = i + 1
            while j < len(v):
                if v[j] == "'":
                    if j + 1 < len(v) and v[j + 1] == "'":
                        s.append("'")
                        j += 2
                        continue
                    break
                s.append(v[j])
                j += 1
            i = j + 1
        elif v[i] == '#':
            j = i + 1
            while j < len(v) and v[j] not in "#'":
                j += 1
            code = v[i + 1:j]
            try:
                s.append(chr(int(code[1:], 16) if code.startswith('$') else int(code)))
            except ValueError:
                pass
            i = j
        else:
            i += 1
    t = ''.join(s)
    return str(ord(t)) if len(t) == 1 else 's:' + t


C_ESC = {'n': '\n', 't': '\t', 'r': '\r', '0': '\0', 'a': '\a', 'b': '\b', 'f': '\f', 'v': '\v', 'e': '\x1b'}


def c_literal(kind, v):
    if kind == 'num':
        w = v.replace("'", '').rstrip('uUlLfF')
        try:
            if w[:2] in ('0x', '0X'):
                return str(int(w[2:], 16))
            if w[:2] in ('0b', '0B'):
                return str(int(w[2:], 2))
            if len(w) > 1 and w[0] == '0' and w.isdigit():
                return str(int(w, 8))
            return str(int(w)) if w.isdigit() else w
        except ValueError:
            return w
    body = v[v.index(v[-1]) + 1:-1]
    s, i = [], 0
    while i < len(body):
        if body[i] == '\\' and i + 1 < len(body):
            e = body[i + 1]
            if e == 'x':
                j = i + 2
                while j < len(body) and body[j] in '0123456789abcdefABCDEF':
                    j += 1
                s.append(chr(int(body[i + 2:j] or '0', 16)))
                i = j
                continue
            if e in '01234567' and e != '0' or (e == '0' and i + 2 < len(body) and body[i + 2] in '01234567'):
                j = i + 1
                while j < len(body) and j < i + 4 and body[j] in '01234567':
                    j += 1
                s.append(chr(int(body[i + 1:j], 8)))
                i = j
                continue
            s.append(C_ESC.get(e, e))
            i += 2
        else:
            s.append(body[i])
            i += 1
    t = ''.join(s)
    return str(ord(t)) if len(t) == 1 else 's:' + t


def lines_of(text):
    """A function: offset -> line number."""
    starts = [0] + [m.end() for m in re.finditer('\n', text)]
    import bisect
    return lambda pos: bisect.bisect_right(starts, pos)


def scan(path):
    """(raw, ren, lit): raw and ren are [(token, line)], lit is [(value, line)]."""
    is_c = path.lower().endswith(CPP)
    src = open(path, encoding='latin-1').read()
    text = strip_c(src) if is_c else strip_pascal(src)
    line = lines_of(text)
    toks, lit = [], []
    for m in (CTOK if is_c else TOK).finditer(text):
        k = m.lastgroup
        v = m.group(k)
        ln = line(m.start())
        if k in ('str', 'chr', 'num') and is_c:
            lit.append((c_literal('num' if k == 'num' else 'str', v), ln))
        if is_c:
            continue
        if k == 'id':
            lv = v.lower()
            toks.append((lv, 'K:' + lv if lv in KEYWORDS else 'ID', ln))
        elif k == 'str':
            toks.append((v.lower(), 'LIT', ln, v))
        elif k == 'num':
            toks.append((v.lower(), 'NUM', ln, v))
        else:
            toks.append((v, v, ln))
    raw, ren = [], []
    i, n = 0, len(toks)
    while i < n:
        v = toks[i][0]
        prev = toks[i - 1][0] if i else ''
        if v in HEADS and prev not in ('=', ':', '(', ','):
            j, depth = i + 1, 0
            while j < n and not (toks[j][0] == ';' and depth == 0):
                depth += {'(': 1, ')': -1}.get(toks[j][0], 0)
                j += 1
            j += 1
            while j + 1 < n and toks[j][0] in DIRECTIVES:
                j += 1
                while j < n and toks[j][0] != ';':
                    j += 1
                j += 1
            h = ('\x00head', path, len(raw))
            lit.append((h, toks[i][2]))
            raw.append((h, toks[i][2]))
            ren.append((h, toks[i][2]))
            i = j
        else:
            raw.append((toks[i][0], toks[i][2]))
            ren.append((toks[i][1], toks[i][2]))
            if toks[i][1] in ('LIT', 'NUM'):
                lit.append((pas_literal('num' if toks[i][1] == 'NUM' else 'str', toks[i][3]), toks[i][2]))
            i += 1
    return raw, ren, lit


def index(seqs, k):
    """{hash of a window of k: (file, line)} over [(file, [(token, line)])]."""
    ix = {}
    for f, seq in seqs:
        words = [t for t, _ in seq]
        for i in range(len(words) - k + 1):
            ix.setdefault(hash(tuple(words[i:i + k])), (f, seq[i][1]))
    return ix


def runs(seq, ix, k, ok=None):
    """The maximal runs of seq whose every window of k is in ix: [(start, end, hit)]."""
    words = [t for t, _ in seq]
    out, i, n = [], 0, len(words) - k + 1
    while i < n:
        hit = ix.get(hash(tuple(words[i:i + k])))
        if hit is None:
            i += 1
            continue
        j = i + 1
        while j < n and hash(tuple(words[j:j + k])) in ix:
            j += 1
        end = j - 1 + k
        if ok is None or ok(words[i:end]):
            out.append((i, end, hit))
        i = end
    return out


def files(paths, exts):
    for p in paths:
        if os.path.isdir(p):
            for root, dirs, names in os.walk(p):
                dirs[:] = sorted(d for d in dirs if not d.startswith('.'))
                for name in sorted(names):
                    if name.lower().endswith(exts):
                        yield os.path.join(root, name)
        elif p.lower().endswith(exts):
            yield p


def main():
    if os.environ.get('PYTHONHASHSEED') != '0':      # the indexes are kept between runs: the hashes must be the same
        os.environ['PYTHONHASHSEED'] = '0'
        os.execv(sys.executable, [sys.executable] + sys.argv)
    ap = argparse.ArgumentParser()
    ap.add_argument('--ref', required=True)
    ap.add_argument('--allowed')
    ap.add_argument('--report')
    ap.add_argument('--max', action='store_true')
    ap.add_argument('--raw-k', type=int, default=RAW_K)
    ap.add_argument('--ren-k', type=int, default=REN_K)
    ap.add_argument('--lit-k', type=int, default=LIT_K)
    ap.add_argument('--lit-distinct', type=int, default=LIT_DISTINCT)
    ap.add_argument('--git-range')
    ap.add_argument('--cache', default='build/audit-cache',
                    help='directory for the indexes of the corpora (default build/audit-cache; "" for none)')
    ap.add_argument('paths', nargs='*')
    a = ap.parse_args()
    refs = [l.strip() for l in open(a.ref, encoding='utf-8') if l.strip()]
    allowed = [l.strip() for l in open(a.allowed, encoding='utf-8') if l.strip()] if a.allowed else []
    import hashlib, pickle
    key = hashlib.sha1(repr((open(__file__, 'rb').read(), a.raw_k, a.ren_k, a.lit_k,
                             [(r, os.path.getmtime(r)) for r in refs + allowed])).encode()).hexdigest()
    cache = os.path.join(a.cache, key + '.pickle') if a.cache else None
    if cache and os.path.isfile(cache):
        with open(cache, 'rb') as fh:
            ix_raw, ix_ren, ix_lit = pickle.load(fh)
    else:
        pas_raw, pas_ren, all_lit = [], [], []
        for r in refs:
            raw, ren, lit = scan(r)
            if r.lower().endswith(CPP):
                all_lit.append((r, lit))
            else:
                pas_raw.append((r, raw))
                pas_ren.append((r, ren))
        ix_raw = index(pas_raw, a.raw_k)
        ix_ren = index(pas_ren, a.ren_k)
        ix_lit = index(all_lit, a.lit_k)
        for r in allowed:
            if r.lower().endswith(DOC):
                seqs = {'lit': doc_literals(r)}
            else:
                raw, ren, lit = scan(r)
                seqs = {'raw': raw, 'ren': ren, 'lit': lit}
            for name, ix, k in (('raw', ix_raw, a.raw_k), ('ren', ix_ren, a.ren_k), ('lit', ix_lit, a.lit_k)):
                if name in seqs:
                    for h in index([(r, seqs[name])], k):
                        ix.pop(h, None)
        if cache:
            os.makedirs(a.cache, exist_ok=True)
            with open(cache + '.part', 'wb') as fh:
                pickle.dump((ix_raw, ix_ren, ix_lit), fh, protocol=pickle.HIGHEST_PROTOCOL)
            os.replace(cache + '.part', cache)
    def significant(v):
        if isinstance(v, tuple):
            return False
        if v.startswith('s:'):
            return len(v) >= 4
        return not v.isdigit() or int(v) >= 32

    def distinct(w):
        if len(set(v for v in w if significant(v))) < a.lit_distinct:
            return False
        steps = 0
        for x, y in zip(w, w[1:]):
            if isinstance(x, str) and isinstance(y, str) and x.isdigit() and y.isdigit() and abs(int(y) - int(x)) == 1:
                steps += 1
        return steps < 0.5 * (len(w) - 1)
    wordy = lambda w: sum(1 for t in w if t == 'ID' or str(t).startswith('K:')) >= REN_WORDS * len(w)
    found, count = [], 0
    work = []
    if a.git_range:
        import subprocess, tempfile
        tmp = tempfile.mkdtemp(prefix='borrow-audit-')
        commits = subprocess.run(['git', 'rev-list', '--reverse', a.git_range], capture_output=True, text=True,
                                 check=True).stdout.split()
        for c in commits:
            names = subprocess.run(['git', 'diff-tree', '--root', '--no-commit-id', '-r', '--name-only',
                                    '--diff-filter=AMR', c], capture_output=True, text=True, check=True).stdout.split('\n')
            for name in names:
                if name.lower().endswith(PAS):
                    data = subprocess.run(['git', 'show', '%s:%s' % (c, name)], capture_output=True, check=True).stdout
                    t = os.path.join(tmp, c[:12], name)
                    os.makedirs(os.path.dirname(t), exist_ok=True)
                    open(t, 'wb').write(data)
                    work.append(t)
    else:
        work = list(files(a.paths, PAS))
    gen = re.compile(r'Generated by (tools/[\w./-]+)')
    for f in work:
        with open(f, encoding='latin-1') as fh:
            m = gen.search(fh.readline())
        if m and os.path.isfile(m.group(1)):
            print('generated by %s (checked by running it again): %s' % (m.group(1), f))
            continue
        count += 1
        raw, ren, lit = scan(f)
        best = {}
        for name, seq, ix, k, ok in (('raw', raw, ix_raw, a.raw_k, None), ('ren', ren, ix_ren, a.ren_k, wordy),
                                     ('lit', lit, ix_lit, a.lit_k, distinct)):
            for s, e, hit in runs(seq, ix, k, ok):
                if a.max:
                    if e - s > best.get(name, (0,))[0]:
                        best[name] = (e - s, seq[s][1], hit)
                else:
                    found.append('%s %5d  %s:%d-%d  ==  %s:%d' % (name, e - s, f, seq[s][1], seq[e - 1][1], hit[0], hit[1]))
        if a.max:
            found.append('%-50s ' % f + '  '.join('%s %d (%d %s:%d)' % (n, b[0], b[1], os.path.basename(b[2][0]), b[2][1])
                                                  for n, b in sorted(best.items())))
    tail = '%d files, %d reference files: %d matches (raw >= %d, ren >= %d, lit >= %d)' % (
        count, len(refs), 0 if a.max else len(found), a.raw_k, a.ren_k, a.lit_k)
    out = '\n'.join(found + [tail])
    print(out)
    if a.report:
        open(a.report, 'w', encoding='utf-8').write(out + '\n')
    sys.exit(1 if found and not a.max else 0)


if __name__ == '__main__':
    main()
