#!/usr/bin/env python3
# Builds src/tvelangdata.inc from langs/lang-*.hl: a language file lists "%include part-NAME" lines, which are replaced by the text of langs/part-NAME.hl.
import glob, os, re, sys
here = os.path.dirname(os.path.abspath(__file__)) + '/..'
os.chdir(here + '/langs')

def expand(path, depth=0):
    if depth > 4:
        sys.exit('includes nested too deep: ' + path)
    out = []
    for line in open(path, encoding='utf-8').read().split('\n'):
        m = re.match(r'%include\s+(\S+)\s*$', line)
        if m:
            out.append(expand(m.group(1) + '.hl', depth + 1))
        else:
            out.append(line)
    return '\n'.join(out)

def pas(text):
    lines = [l for l in text.split('\n')]
    parts = []
    for l in lines:
        parts.append("'" + l.replace("'", "''") + "'")
    return " + #10 +\n    ".join(parts)

files = sorted(glob.glob('lang-*.hl'))
res = ['{ Generated by tools/gen-langs.py from langs/*.hl; do not edit. }', '']
res.append('const')
res.append('  TveLangCount = %d;' % len(files))
res.append('')
for i, f in enumerate(files):
    res.append('  TveLangText%d =\n    %s;' % (i, pas(expand(f))))
    res.append('')
res.append('  TveLangTexts: array[0..%d] of AnsiString = (' % (len(files) - 1))
res.append(',\n'.join('    TveLangText%d' % i for i in range(len(files))))
res.append('  );')
open(here + '/src/tvelangdata.inc', 'w', encoding='utf-8').write('\n'.join(res) + '\n')
print('%d languages' % len(files))
